# Generated by Django 5.0.1 on 2024-01-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info", models.CharField(max_length=255, null=True)),
                ("num_seats", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "buses",
            },
        ),
    ]
