# Generated by Django 5.0.1 on 2024-01-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0003_alter_ticket_order_alter_ticket_trip_alter_trip_bus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
