# Generated by Django 5.0.1 on 2024-01-23 13:13

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0005_alter_ticket_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="image",
            field=models.ImageField(
                null=True, upload_to=station.models.bus_image_file_path
            ),
        ),
    ]
