# Generated by Django 5.0.1 on 2024-01-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0006_bus_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="facilities",
            field=models.ManyToManyField(
                blank=True, related_name="buses", to="station.facility"
            ),
        ),
    ]
